ALTER TABLE `Product`
  MODIFY COLUMN `price` DECIMAL(18, 2) NOT NULL,
  MODIFY COLUMN `originalPrice` DECIMAL(18, 2) NULL;

ALTER TABLE `ProductVariant`
  MODIFY COLUMN `price` DECIMAL(18, 2) NOT NULL,
  MODIFY COLUMN `originalPrice` DECIMAL(18, 2) NULL;

ALTER TABLE `Order`
  MODIFY COLUMN `totalAmount` DECIMAL(18, 2) NOT NULL,
  MODIFY COLUMN `depositAmount` DECIMAL(18, 2) NULL,
  MODIFY COLUMN `subtotal` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  MODIFY COLUMN `shippingFee` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  MODIFY COLUMN `couponDiscount` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  MODIFY COLUMN `pointDiscount` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  MODIFY COLUMN `amountPaid` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  MODIFY COLUMN `amountDue` DECIMAL(18, 2) NOT NULL DEFAULT 0,
  MODIFY COLUMN `discountAmount` DECIMAL(18, 2) NOT NULL DEFAULT 0;

ALTER TABLE `PaymentTransaction`
  MODIFY COLUMN `amount` DECIMAL(18, 2) NOT NULL;

ALTER TABLE `OrderItem`
  MODIFY COLUMN `priceAtPurchase` DECIMAL(18, 2) NOT NULL;

ALTER TABLE `Commission`
  MODIFY COLUMN `amount` DECIMAL(18, 2) NOT NULL;

ALTER TABLE `InventoryTransaction`
  MODIFY COLUMN `costPrice` DECIMAL(18, 2) NULL;
